### ISSUE TITLE
Keycloak 25 - Escape Slashes Environment Variable

### ISSUE THREAD

**Issue by UnicornChance** [defenseunicorns/uds-identity-config#118]
## Description

Once we've updated to using Keycloak 25, we need to make sure and utilize the environment variable made available in kc25 for escaping slashes in group names:

https://www.keycloak.org/docs/latest/upgrading/index.html#escaping-slashes-in-group-paths

re-evaluate if the changes made in [this PR](https://github.com/defenseunicorns/uds-identity-config/pull/111)  are relevant with the use of the env var.

### Code:
```yaml
            # Escape Slashes in Group Names
            - name: KC_SPI_GROUP_JPA_ESCAPE_SLASHES_IN_GROUP_PATH
              value: "true"
```
