### ISSUE TITLE
Add basic smoke test for config changes

### ISSUE THREAD

**Issue by UnicornChance** [defenseunicorns/uds-identity-config#27]
## New Feature
Need to add a/some basic smoke tests for making changes to the config so that it doesn't just break uds-core when it gets there.

### Describe the solution you'd like
A generic build of identity-config image and use that image to successfully deploy keycloak. 

Create task for building uds-core and then testing the new image with keycloak, update docs as well to represent that new task and how to use it.

### Additional Background Info
Further e2e/integration tests are not captured in this and will be implemented in uds-core repo.

**Comment by rjferguson21** [comment]
I think a good option might be to test against the updated core-istio bundle that includes keycloak - https://github.com/defenseunicorns/uds-core/pull/262

I've been testing using this zarf.yaml
```yaml
kind: ZarfPackageConfig
metadata:
  name: identity-config
  description: Identity Config

components:
  - name: identity-config
    required: true
    actions:
      onDeploy:
        after:
          - cmd: |
              kubectl set image sts/keycloak uds-config=uds-core-config:keycloak --namespace=keycloak
    images:
      - uds-core-config:keycloak
 ```
 
 with this task (includes full uds-core which is probably not appropriate for CI in the uds-identity-config repo):
 
 ```yaml
   - name: uds-core-integration-test
    description: "UDS Core integration test"
    actions:
      - cmd: uds deploy ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core-demo:0.15.1 --confirm
      - task: dev-build
      - cmd: uds zarf package create . --confirm && uds zarf package deploy zarf-package-identity-* --confirm
 ``
