### ISSUE TITLE
Add support for the AWS Load Balancer mTLS

### ISSUE THREAD

**Issue by slaskawi** [defenseunicorns/uds-identity-config#470]
## Summary

As highlighted in https://github.com/keycloak/keycloak/issues/25579, Keycloak doesn't support AWS Load Balancer (ALB) mTLS certificate proxying. 

Supporting such a certificate handling requires reading the `x-amzn-mtls-clientcert` that contains URL Encoded, Base64 encoded certificate (so the implementation needs to first, URL decode it to a `String` and then perform `base64` decoding. 

This ticket contains the following subtasks:

- [ ] Establish path forward for this issue with the Keycloak Team. Potential solutions are:
  - Implementing this as a Keycloak Extension
  - Implementing this directly in Keycloak, potentially extending the `NginxProxySslClientCertificateLookupFactory` implementation with base64 decoding and overriding headers
  - [ ] Agree with @eddiezane and his team on the path forward
  - [ ] Proceed with the implementation and test it on EKS

## Existing workaround for Istio

There is a workaround for this issue today, which requires using Envoy Filter. @eddiezane was kind enough to share the implementation:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: alb-clientcert-parse
  namespace: keycloak
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
        portNumber: 8080
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          defaultSourceCode:
            inlineString: |
              function url_decode(str)
                str = string.gsub(str, "%%(%x%x)", function(h) return string.char(tonumber(h,16)) end)
                str = string.gsub(str, "\r\n", "\n")
                return str
              end

              function envoy_on_request(request_handle)
                local raw_cert = request_handle:headers():get("x-amzn-mtls-clientcert")
                if raw_cert ~= nil and raw_cert ~= "" then
                  local decoded = url_decode(raw_cert)
                  local encoded = request_handle:base64Escape(decoded)
                  request_handle:headers():add("x-client-cert", encoded)
                end
              end
```
