### ISSUE TITLE
broken protocol mapper view

### ISSUE THREAD

**Issue by UnicornChance** [defenseunicorns/uds-identity-config#481]
### Steps to reproduce
1. Create a client that includes an **`oidc-audience-mapper`** (example YAML below).  
2. In the Admin Console open **Clients → _\<your-client\>_ → Dedicated scopes**.  
3. Click the mapper whose type is **`oidc-audience-mapper`** to view its details.

---

### Expected result
The *Mapper details* page renders and lets me view / edit the mapper.

---

### Actual result
A red banner appears and the page stops rendering:
```
(intermediate value).map is not a function
```

![Image](https://github.com/user-attachments/assets/e67a1719-2d31-481b-a26a-2df8abc6fed3)

### More Context
```
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
 name: prometheus-blackbox-exporter
 namespace: {{ .Release.Namespace }}
spec:
 sso:
   - name: prometheus-blackbox-exporter
     clientId: uds-package-blackbox-exporter
     standardFlowEnabled: false
     serviceAccountsEnabled: true
     alwaysDisplayInConsole: true
     protocolMappers:
        - name: ${clientId}
          protocol: \"openid-connect\"
          protocolMapper: \"oidc-audience-mapper\"
          config:
            included.client.audience: \"${clientId}\"
            access.token.claim: \"true\"
            introspection.token.claim: \"true\"
            id.token.claim: \"false\"
            lightweight.claim: \"false\"
            userinfo.token.claim: \"false\"
```
